// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJIjXKwEQcMbzAdqiGts-A2BUmXD6pYAA',
    appId: '1:241159168668:web:87b559830fac89331b0359',
    messagingSenderId: '241159168668',
    projectId: 'flutter-lovers-b2344',
    authDomain: 'flutter-lovers-b2344.firebaseapp.com',
    storageBucket: 'flutter-lovers-b2344.appspot.com',
    measurementId: 'G-3E17CTLWCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrV5jt3mMqybQxObZMUWGAKTg-sH-F7W4',
    appId: '1:241159168668:android:119b327816139a051b0359',
    messagingSenderId: '241159168668',
    projectId: 'flutter-lovers-b2344',
    storageBucket: 'flutter-lovers-b2344.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwq6leGpM4sJsBg0kKSv_cu5SkUcNqz7A',
    appId: '1:241159168668:ios:f67a132cb2a6a52a1b0359',
    messagingSenderId: '241159168668',
    projectId: 'flutter-lovers-b2344',
    storageBucket: 'flutter-lovers-b2344.appspot.com',
    iosBundleId: 'com.example.flutterLovers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwq6leGpM4sJsBg0kKSv_cu5SkUcNqz7A',
    appId: '1:241159168668:ios:1e320560766e79421b0359',
    messagingSenderId: '241159168668',
    projectId: 'flutter-lovers-b2344',
    storageBucket: 'flutter-lovers-b2344.appspot.com',
    iosBundleId: 'com.example.flutterLovers.RunnerTests',
  );
}
